<a href="https://numpy.org/">Numpy Documenation</a><br>
<a href="https://numpy.org/devdocs/user/quickstart.html">Tutorial</a>

In [2]:
import numpy as np

>Key Points
<ol>
<li>NumPy’s main object is the homogeneous multidimensional array.</li>
<li>In NumPy dimensions are called <b>axes</b>.</li>
<li>NumPy’s array class is called <b>ndarray</b>.</li>
</ol>

>Important Attributes of ndarray object are:
1. ndim
2. shape
3. size
4. shape
5. itemsize
6. data

#### Array Creation functions

1. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array">array</a>
2. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html#numpy.empty_like">empty_like</a>
3. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html#numpy.ones_like">ones_like</a>
4. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html#numpy.zeros_like">zeroes_like</a>
5. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.full_like.html#numpy.full_like">full_like</a>
6. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty">empty</a>
7. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones">ones</a>
8. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros">zeros</a>
9. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html#numpy.full">full</a>
---
10. <a href="https://jakevdp.github.io/PythonDataScienceHandbook/02.09-structured-data-numpy.html">Structured Data: NumPy's Structured Arrays</a>

---

11. <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html#numpy.arange">arange</a>
12. <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html#numpy.linspace">linspace</a>

---

13. <a href="https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html">*Random</a>

---
14. <a href="https://numpy.org/devdocs/reference/generated/numpy.fromfunction.html#numpy.fromfunction">fromfunction</a>
15. <a href="https://numpy.org/devdocs/reference/generated/numpy.fromfile.html#numpy.fromfile">fromfile</a>

---
16. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape">ndarray.reshape</a>
17. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html">numpy.reshape</a>
---
18. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html#numpy-set-printoptions">set_printoptions</a>
---
19. <a href="https://numpy.org/devdocs/user/quickstart.html#basic-operations">Basic Operations</a>
---
20. <a href="https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating">Indexing, slicing and Iterating</a>
21. <a href="https://numpy.org/devdocs/user/quickstart.html#shape-manipulation">Shape manipulation:ndarray.shape, reshape, resize, ravel</a>
---
22. <a href="https://numpy.org/devdocs/user/quickstart.html#functions-and-methods-overview">Functions methods & Overview</a>
---
23. <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.set.html">Set Operations on numpy arrays</a>

In [121]:
#array
nparray_from_pylist = np.array([1,2,3,4,5,6])
nparray_from_pytuple = np.array((1,2,3,4,5,6))
print(nparray_from_pylist)
print(nparray_from_pytuple)

nparray_dtype = np.array([1,2,3,4,5,6],dtype=np.float64)
print(nparray_dtype)

nparray_multidimensional = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(nparray_multidimensional)

nparray_ndim = np.array([[1,2,3],[4,5,6]],ndmin=3)
print(nparray_ndim)
print(nparray_ndim.size)
print(nparray_ndim.shape)

nparray_empty = np.empty((3,3))
print(nparray_empty)
nparray_empty_like = np.empty_like(nparray_empty,dtype=np.int64)
print(nparray_empty_like)

nparray_zeros = np.zeros((3,3),dtype=np.int64)
print(nparray_zeros)
nparray_zeros_like = np.zeros_like(nparray_zeros,dtype=np.float64)
print(nparray_zeros_like)

nparray_ones = np.ones((3,3),dtype=np.float64)
print(nparray_ones)
nparray_ones_like = np.ones_like(nparray_ones, dtype=np.int16)
print(nparray_ones_like)

nparray_full = np.full(6,0.1)
print(nparray_full)
nparray_full_like = np.full_like(nparray_full,3.8,dtype=np.int64)
print(nparray_full_like)
nparray_full = np.full((3,2),0.1)
print(nparray_full)
nparray_full_like = np.full_like(nparray_full,3.8,dtype=np.int64)
print(nparray_full_like)

nparray_arange = np.arange(10)
print(nparray_arange)

nparray_linspace = np.linspace(0.0, 1.5,20)
print(nparray_linspace)

nparray_rand = np.random.rand(2,3,4)
print(nparray_rand)

#Mean-0 variance-1
nparray_randn = np.random.randn(10)
print(nparray_randn)
nparray_randn = np.random.randn(1,2,3)
print(nparray_randn)
#For random samples from N(\mu, \sigma^2), use:
#sigma * np.random.randn(...) + mu
#Mean-5 variance-1
nparray_randn =1*np.random.randn(10)+5
print(nparray_randn)

nparray_ndarray_reshape = np.arange(10).reshape(2,5)
print(nparray_ndarray_reshape)

nparray_numpy_reshape = np.reshape(nparray_ndarray_reshape,(5,2))
print(nparray_numpy_reshape)


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[1 2 3]
  [4 5 6]]]
6
(1, 2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0.1 0.1 0.1 0.1 0.1 0.1]
[3 3 3 3 3 3]
[[0.1 0.1]
 [0.1 0.1]
 [0.1 0.1]]
[[3 3]
 [3 3]
 [3 3]]
[0 1 2 3 4 5 6 7 8 9]
[0.         0.07894737 0.15789474 0.23684211 0.31578947 0.39473684
 0.47368421 0.55263158 0.63157895 0.71052632 0.78947368 0.86842105
 0.94736842 1.02631579 1.10526316 1.18421053 1.26315789 1.34210526
 1.42105263 1.5       ]
[[[0.51697252 0.0348674  0.51414527 0.12019085]
  [0.27529236 0.68874408 0.64414535 0.02551836]
  [0.6507366  0.32860161 0.04696607 0.456844  ]]

 [[0.75838535 0.93811248 0.48806849

##### Numpy Exercises
<a href="https://www.machinelearningplus.com/python/101-numpy-exercises-python/"> Q & A Practice</a>

In [2]:
#1 Import numpy as np and print the version number
import numpy as np
print(np.__version__)

1.18.1


In [123]:
#2 Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [124]:
#3 Create a 3×3 numpy array of all True’s
bool_arr = np.full((3,3),True,dtype=bool)
print(bool_arr)

#Alternate Method
bool_arr = np.ones((3,3),dtype=bool)
print(bool_arr)
#With False
bool_arr_false = np.zeros((3,3),dtype=bool)
print(bool_arr_false)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]


In [125]:
#4  Extract all odd numbers from arr
print(arr[arr%2==1])

[1 3 5 7 9]


In [126]:
#5  Replace all odd numbers in arr with -1
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [127]:
#6 Replace all odd numbers in arr with -1 without changing arr
#Using where
out_arr = np.where(arr%2==1,-1,arr)
print(arr)
print(out_arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [128]:
#7 Convert a 1D array to a 2D array with 2 rows
reshaped_arr = arr.reshape(2,5) 
'''Alternative way arr.reshape(2,-1)'''
print(reshaped_arr)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


In [129]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)

In [130]:
#8 Stack arrays a and b vertically
vstack_ab = np.vstack((a,b))
'''
Alternative ways:
np.concatenate([a, b], axis=0)
np.r_[a, b]
'''
print(vstack_ab)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [131]:
#9 Stack the arrays a and b horizontally.
hstack_ab = np.hstack([a,b])
'''
Alternative ways
print(np.concatenate([a, b], axis=1))
print(np.c_[a, b])
'''
print(hstack_ab)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [132]:
#10 Create the following pattern without hardcoding. Use only numpy functions and the below input array a
'''
a = np.array([1,2,3])
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
'''
a=np.array([1,2,3])
pattern1 = np.r_[np.repeat(a,3),np.tile(a,3)]
print(pattern1)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [133]:
#11 Get the common items between a and b
a1d = np.array([1,2,3,2,3,4,3,4,5,6])
b1d = np.array([7,2,10,2,7,4,9,4,9,8])
common_ab = np.intersect1d(a1d,b1d)
print(common_ab)

# a2d = np.array([1,2,3,2,3,4,3,4,5,6]).reshape(2,5)
# b2d = np.array([7,2,10,2,7,4,9,4,9,8]).reshape(2,5)
# common_ab=np.intersect2d(a2d,b2d)
# print(common_ab)



[2 4]


In [134]:
#12 From array a remove all items present in array b
a1d = np.array([1,2,3,4,5])
b1d = np.array([5,6,7,8,9])
setdiff_ab = np.setdiff1d(a1d,b1d)
print(setdiff_ab)

[1 2 3 4]


In [135]:
#13 Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
positions_ab=np.where(a==b)
print(positions_ab)

(array([1, 3, 5, 7], dtype=int32),)


In [136]:
#14 Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
between_range_in_array = a[np.where((a>=5) & (a<=10))]
print(between_range_in_array)

[ 6  9 10]


In [137]:
#15 Convert the function maxx that works on two scalars, to work on two arrays.

#Function maxx
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

#Use vectorize
pair_max = np.vectorize(maxx, otypes=[int])
# pair_max = np.vectorize(maxx, otypes=[float]) #For float
max_ab = pair_max(a,b)
print(max_ab)

[6 7 9 8 9 7 5]


In [138]:
arr = np.arange(9).reshape(3,3)

In [139]:
#16 Swap columns 1 and 2 in the array arr.
arr_col_swap = arr[:,[1,0,2]]
print(arr_col_swap)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [140]:
#17 Swap rows 1 and 2 in the array arr
arr_row_swap = arr[[1,0,2],:]
print(arr_row_swap)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [141]:
#18 Reverse the rows of a 2D array arr.
arr_row_reverse = arr[::-1,:]
print(arr_row_reverse)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [142]:
#19 Reverse the columns of a 2D array arr.
arr_col_reverse = arr[:,::-1]
print(arr_col_reverse)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [143]:
#20 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
random_2d_float_arr = np.random.randint(5,10,(5,3))+np.random.random((5,3))
'''
Another way:
random_2d_float_arr = np.random.uniform(5,10, size=(5,3))
'''
print(random_2d_float_arr)

[[8.74644132 5.05533209 6.30029112]
 [7.82719638 5.83656737 8.62494695]
 [7.91309762 8.69221266 6.30082794]
 [6.05515282 8.80131216 6.55562104]
 [7.77815242 8.52784336 6.59865329]]


In [3]:
#21 Print or show only 3 decimal places of the numpy array rand_arr
rand_arr = np.random.uniform()
np.set_printoptions(precision=3)
print(rand_arr)

0.8971484186768155


In [5]:
#22 Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)
print(rand_arr)

[[0.001 0.    0.   ]
 [0.001 0.    0.   ]
 [0.001 0.001 0.   ]]


In [6]:
#23 Limit the number of items printed in python numpy array a to a maximum of 6 elements.
arr=np.arange(15)
np.set_printoptions(threshold=6)
print(arr)

[ 0  1  2 ... 12 13 14]


In [8]:
#24 Print the full numpy array a without truncating.
import sys
np.set_printoptions(threshold=sys.maxsize)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
#25 Import the iris dataset keeping the text intact.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

url_local = 'C:/Users/Admin/Desktop/Learning/Data Science/DataSets'
# iris_local = np.fromfile(url_local,sep=',')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:4])
# print(iris_local[:4])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']]


In [6]:
#26 Extract the text column species from the 1D iris imported in previous question.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species = [i[4] for i in iris]
print(species[:5])

[b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa']


In [13]:
#27 Convert the 1D iris to 2D array iris_2d by omitting the species text field.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None,encoding=None)
print(iris_1d[4])
iris_2d = [list(i)[:4] for i in iris_1d]
'''
Alternative way:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
'''
print(iris_2d[:4])

## Need to check this. *

(5., 3.6, 1.4, 0.2, 'Iris-setosa')
[[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2]]


In [15]:
#28  Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype=None,encoding=None,usecols=[0])

mean=np.mean(sepallength)
median=np.median(sepallength)
standard_deviation=np.std(sepallength)

print(mean)
print(median)
print(standard_deviation)

5.843333333333334
5.8
0.8253012917851409
