<a href="https://numpy.org/">Numpy Documenation</a><br>
<a href="https://numpy.org/devdocs/user/quickstart.html">Tutorial</a>

In [2]:
import numpy as np

>Key Points
<ol>
<li>NumPy’s main object is the homogeneous multidimensional array.</li>
<li>In NumPy dimensions are called <b>axes</b>.</li>
<li>NumPy’s array class is called <b>ndarray</b>.</li>
</ol>

>Important Attributes of ndarray object are:
1. ndim
2. shape
3. size
4. shape
5. itemsize
6. data

#### Array Creation functions

1. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array">array</a>
2. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html#numpy.empty_like">empty_like</a>
3. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html#numpy.ones_like">ones_like</a>
4. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html#numpy.zeros_like">zeroes_like</a>
5. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.full_like.html#numpy.full_like">full_like</a>
6. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty">empty</a>
7. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones">ones</a>
8. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros">zeros</a>
9. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html#numpy.full">full</a>
---
10. <a href="https://jakevdp.github.io/PythonDataScienceHandbook/02.09-structured-data-numpy.html">Structured Data: NumPy's Structured Arrays</a>

---

11. <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html#numpy.arange">arange</a>
12. <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html#numpy.linspace">linspace</a>

---

13. <a href="https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html">*Random</a>

---
14. <a href="https://numpy.org/devdocs/reference/generated/numpy.fromfunction.html#numpy.fromfunction">fromfunction</a>
15. <a href="https://numpy.org/devdocs/reference/generated/numpy.fromfile.html#numpy.fromfile">fromfile</a>

---
16. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape">ndarray.reshape</a>
17. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html">numpy.reshape</a>
---
18. set_printoptions ^
---
19. <a href="https://numpy.org/devdocs/user/quickstart.html#basic-operations">Basic Operations</a>
---
20. <a href="https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating">Indexing, slicing and Iterating</a>
21. <a href="https://numpy.org/devdocs/user/quickstart.html#shape-manipulation">Shape manipulation:ndarray.shape, reshape, resize, ravel</a>
---
22. <a href="https://numpy.org/devdocs/user/quickstart.html#functions-and-methods-overview">Functions methods & Overview</a>

In [56]:
#array
nparray_from_pylist = np.array([1,2,3,4,5,6])
nparray_from_pytuple = np.array((1,2,3,4,5,6))
print(nparray_from_pylist)
print(nparray_from_pytuple)

nparray_dtype = np.array([1,2,3,4,5,6],dtype=np.float64)
print(nparray_dtype)

nparray_multidimensional = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(nparray_multidimensional)

nparray_ndim = np.array([[1,2,3],[4,5,6]],ndmin=3)
print(nparray_ndim)
print(nparray_ndim.size)
print(nparray_ndim.shape)

nparray_empty = np.empty((3,3))
print(nparray_empty)
nparray_empty_like = np.empty_like(nparray_empty,dtype=np.int64)
print(nparray_empty_like)

nparray_zeros = np.zeros((3,3),dtype=np.int64)
print(nparray_zeros)
nparray_zeros_like = np.zeros_like(nparray_zeros,dtype=np.float64)
print(nparray_zeros_like)

nparray_ones = np.ones((3,3),dtype=np.float64)
print(nparray_ones)
nparray_ones_like = np.ones_like(nparray_ones, dtype=np.int16)
print(nparray_ones_like)

nparray_full = np.full(6,0.1)
print(nparray_full)
nparray_full_like = np.full_like(nparray_full,3.8,dtype=np.int64)
print(nparray_full_like)
nparray_full = np.full((3,2),0.1)
print(nparray_full)
nparray_full_like = np.full_like(nparray_full,3.8,dtype=np.int64)
print(nparray_full_like)

nparray_arange = np.arange(10)
print(nparray_arange)

nparray_linspace = np.linspace(0.0, 1.5,20)
print(nparray_linspace)

nparray_rand = np.random.rand(2,3,4)
print(nparray_rand)

#Mean-0 variance-1
nparray_randn = np.random.randn(10)
print(nparray_randn)
nparray_randn = np.random.randn(1,2,3)
print(nparray_randn)
#For random samples from N(\mu, \sigma^2), use:
#sigma * np.random.randn(...) + mu
#Mean-5 variance-1
nparray_randn =1*np.random.randn(10)+5
print(nparray_randn)

nparray_ndarray_reshape = np.arange(10).reshape(2,5)
print(nparray_ndarray_reshape)

nparray_numpy_reshape = np.reshape(nparray_ndarray_reshape,(5,2))
print(nparray_numpy_reshape)


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[1 2 3]
  [4 5 6]]]
6
(1, 2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0.1 0.1 0.1 0.1 0.1 0.1]
[3 3 3 3 3 3]
[[0.1 0.1]
 [0.1 0.1]
 [0.1 0.1]]
[[3 3]
 [3 3]
 [3 3]]
[0 1 2 3 4 5 6 7 8 9]
[0.         0.07894737 0.15789474 0.23684211 0.31578947 0.39473684
 0.47368421 0.55263158 0.63157895 0.71052632 0.78947368 0.86842105
 0.94736842 1.02631579 1.10526316 1.18421053 1.26315789 1.34210526
 1.42105263 1.5       ]
[[[0.76503218 0.36429618 0.28831867 0.68630838]
  [0.15190604 0.22235366 0.53645923 0.80747174]
  [0.79920456 0.54240462 0.83301019 0.10974949]]

 [[0.7496847  0.62804504 0.83590256

##### Numpy Exercises
<a href="https://www.machinelearningplus.com/python/101-numpy-exercises-python/"> Q & A Practice</a>

In [60]:
#1
import numpy as np
print(np.__version__)

1.18.1


In [67]:
#2
arr = np.arange(10)
print(oned_array)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
#3
bool_arr = np.full((3,3),True,dtype=bool)
print(bool_arr)

#Alternate Method
bool_arr = np.ones((3,3),dtype=bool)
print(bool_arr)
#With False
bool_arr_false = np.zeros((3,3),dtype=bool)
print(bool_arr_false)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]


In [70]:
#4
print(arr[arr%2==1])

[1 3 5 7 9]


In [71]:
#5
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
