<a href="https://numpy.org/">Numpy Documenation</a><br>
<a href="https://numpy.org/devdocs/user/quickstart.html">Tutorial</a>

In [2]:
import numpy as np

>Key Points
<ol>
<li>NumPy’s main object is the homogeneous multidimensional array.</li>
<li>In NumPy dimensions are called <b>axes</b>.</li>
<li>NumPy’s array class is called <b>ndarray</b>.</li>
</ol>

>Important Attributes of ndarray object are:
1. ndim
2. shape
3. size
4. shape
5. itemsize
6. data

#### Array Creation functions

1. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array">array</a>
2. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html#numpy.empty_like">empty_like</a>
3. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html#numpy.ones_like">ones_like</a>
4. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html#numpy.zeros_like">zeroes_like</a>
5. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.full_like.html#numpy.full_like">full_like</a>
6. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty">empty</a>
7. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones">ones</a>
8. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros">zeros</a>
9. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html#numpy.full">full</a>
---
10. <a href="https://jakevdp.github.io/PythonDataScienceHandbook/02.09-structured-data-numpy.html">Structured Data: NumPy's Structured Arrays</a>

---

11. <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html#numpy.arange">arange</a>
12. <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html#numpy.linspace">linspace</a>

---

13. <a href="https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html">*Random</a>

---
14. <a href="https://numpy.org/devdocs/reference/generated/numpy.fromfunction.html#numpy.fromfunction">fromfunction</a>
15. <a href="https://numpy.org/devdocs/reference/generated/numpy.fromfile.html#numpy.fromfile">fromfile</a>

---
16. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape">ndarray.reshape</a>
17. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html">numpy.reshape</a>
---
18. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html#numpy-set-printoptions">set_printoptions</a>
---
19. <a href="https://numpy.org/devdocs/user/quickstart.html#basic-operations">Basic Operations</a>
---
20. <a href="https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating">Indexing, slicing and Iterating</a>
21. <a href="https://numpy.org/devdocs/user/quickstart.html#shape-manipulation">Shape manipulation:ndarray.shape, reshape, resize, ravel</a>
---
22. <a href="https://numpy.org/devdocs/user/quickstart.html#functions-and-methods-overview">Functions methods & Overview</a>
---
23. <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.set.html">Set Operations on numpy arrays</a>
---
24. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html#numpy-where">where*</a>
25. <a href="https://note.nkmk.me/en/python-numpy-where/">where *</a>
---
26. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html#numpy-corrcoef">correlation coefficient</a>
---
27. <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.digitize.html#numpy-digitize">digitize</a>
28. <a href="https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it">np.newaxis</a>

In [121]:
#array
nparray_from_pylist = np.array([1,2,3,4,5,6])
nparray_from_pytuple = np.array((1,2,3,4,5,6))
print(nparray_from_pylist)
print(nparray_from_pytuple)

nparray_dtype = np.array([1,2,3,4,5,6],dtype=np.float64)
print(nparray_dtype)

nparray_multidimensional = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(nparray_multidimensional)

nparray_ndim = np.array([[1,2,3],[4,5,6]],ndmin=3)
print(nparray_ndim)
print(nparray_ndim.size)
print(nparray_ndim.shape)

nparray_empty = np.empty((3,3))
print(nparray_empty)
nparray_empty_like = np.empty_like(nparray_empty,dtype=np.int64)
print(nparray_empty_like)

nparray_zeros = np.zeros((3,3),dtype=np.int64)
print(nparray_zeros)
nparray_zeros_like = np.zeros_like(nparray_zeros,dtype=np.float64)
print(nparray_zeros_like)

nparray_ones = np.ones((3,3),dtype=np.float64)
print(nparray_ones)
nparray_ones_like = np.ones_like(nparray_ones, dtype=np.int16)
print(nparray_ones_like)

nparray_full = np.full(6,0.1)
print(nparray_full)
nparray_full_like = np.full_like(nparray_full,3.8,dtype=np.int64)
print(nparray_full_like)
nparray_full = np.full((3,2),0.1)
print(nparray_full)
nparray_full_like = np.full_like(nparray_full,3.8,dtype=np.int64)
print(nparray_full_like)

nparray_arange = np.arange(10)
print(nparray_arange)

nparray_linspace = np.linspace(0.0, 1.5,20)
print(nparray_linspace)

nparray_rand = np.random.rand(2,3,4)
print(nparray_rand)

#Mean-0 variance-1
nparray_randn = np.random.randn(10)
print(nparray_randn)
nparray_randn = np.random.randn(1,2,3)
print(nparray_randn)
#For random samples from N(\mu, \sigma^2), use:
#sigma * np.random.randn(...) + mu
#Mean-5 variance-1
nparray_randn =1*np.random.randn(10)+5
print(nparray_randn)

nparray_ndarray_reshape = np.arange(10).reshape(2,5)
print(nparray_ndarray_reshape)

nparray_numpy_reshape = np.reshape(nparray_ndarray_reshape,(5,2))
print(nparray_numpy_reshape)


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[1 2 3]
  [4 5 6]]]
6
(1, 2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0.1 0.1 0.1 0.1 0.1 0.1]
[3 3 3 3 3 3]
[[0.1 0.1]
 [0.1 0.1]
 [0.1 0.1]]
[[3 3]
 [3 3]
 [3 3]]
[0 1 2 3 4 5 6 7 8 9]
[0.         0.07894737 0.15789474 0.23684211 0.31578947 0.39473684
 0.47368421 0.55263158 0.63157895 0.71052632 0.78947368 0.86842105
 0.94736842 1.02631579 1.10526316 1.18421053 1.26315789 1.34210526
 1.42105263 1.5       ]
[[[0.51697252 0.0348674  0.51414527 0.12019085]
  [0.27529236 0.68874408 0.64414535 0.02551836]
  [0.6507366  0.32860161 0.04696607 0.456844  ]]

 [[0.75838535 0.93811248 0.48806849

##### Numpy Exercises
<a href="https://www.machinelearningplus.com/python/101-numpy-exercises-python/"> Q & A Practice</a>

In [2]:
#1 Import numpy as np and print the version number
import numpy as np
print(np.__version__)

1.18.1


In [123]:
#2 Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [124]:
#3 Create a 3×3 numpy array of all True’s
bool_arr = np.full((3,3),True,dtype=bool)
print(bool_arr)

#Alternate Method
bool_arr = np.ones((3,3),dtype=bool)
print(bool_arr)
#With False
bool_arr_false = np.zeros((3,3),dtype=bool)
print(bool_arr_false)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]


In [125]:
#4  Extract all odd numbers from arr
print(arr[arr%2==1])

[1 3 5 7 9]


In [126]:
#5  Replace all odd numbers in arr with -1
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [127]:
#6 Replace all odd numbers in arr with -1 without changing arr
#Using where
out_arr = np.where(arr%2==1,-1,arr)
print(arr)
print(out_arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [128]:
#7 Convert a 1D array to a 2D array with 2 rows
reshaped_arr = arr.reshape(2,5) 
'''Alternative way arr.reshape(2,-1)'''
print(reshaped_arr)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


In [129]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)

In [130]:
#8 Stack arrays a and b vertically
vstack_ab = np.vstack((a,b))
'''
Alternative ways:
np.concatenate([a, b], axis=0)
np.r_[a, b]
'''
print(vstack_ab)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [131]:
#9 Stack the arrays a and b horizontally.
hstack_ab = np.hstack([a,b])
'''
Alternative ways
print(np.concatenate([a, b], axis=1))
print(np.c_[a, b])
'''
print(hstack_ab)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [132]:
#10 Create the following pattern without hardcoding. Use only numpy functions and the below input array a
'''
a = np.array([1,2,3])
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
'''
a=np.array([1,2,3])
pattern1 = np.r_[np.repeat(a,3),np.tile(a,3)]
print(pattern1)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [133]:
#11 Get the common items between a and b
a1d = np.array([1,2,3,2,3,4,3,4,5,6])
b1d = np.array([7,2,10,2,7,4,9,4,9,8])
common_ab = np.intersect1d(a1d,b1d)
print(common_ab)

# a2d = np.array([1,2,3,2,3,4,3,4,5,6]).reshape(2,5)
# b2d = np.array([7,2,10,2,7,4,9,4,9,8]).reshape(2,5)
# common_ab=np.intersect2d(a2d,b2d)
# print(common_ab)



[2 4]


In [134]:
#12 From array a remove all items present in array b
a1d = np.array([1,2,3,4,5])
b1d = np.array([5,6,7,8,9])
setdiff_ab = np.setdiff1d(a1d,b1d)
print(setdiff_ab)

[1 2 3 4]


In [135]:
#13 Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
positions_ab=np.where(a==b)
print(positions_ab)

(array([1, 3, 5, 7], dtype=int32),)


In [136]:
#14 Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
between_range_in_array = a[np.where((a>=5) & (a<=10))]
print(between_range_in_array)

[ 6  9 10]


In [137]:
#15 Convert the function maxx that works on two scalars, to work on two arrays.

#Function maxx
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

#Use vectorize
pair_max = np.vectorize(maxx, otypes=[int])
# pair_max = np.vectorize(maxx, otypes=[float]) #For float
max_ab = pair_max(a,b)
print(max_ab)

[6 7 9 8 9 7 5]


In [138]:
arr = np.arange(9).reshape(3,3)

In [139]:
#16 Swap columns 1 and 2 in the array arr.
arr_col_swap = arr[:,[1,0,2]]
print(arr_col_swap)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [140]:
#17 Swap rows 1 and 2 in the array arr
arr_row_swap = arr[[1,0,2],:]
print(arr_row_swap)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [141]:
#18 Reverse the rows of a 2D array arr.
arr_row_reverse = arr[::-1,:]
print(arr_row_reverse)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [142]:
#19 Reverse the columns of a 2D array arr.
arr_col_reverse = arr[:,::-1]
print(arr_col_reverse)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [143]:
#20 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
random_2d_float_arr = np.random.randint(5,10,(5,3))+np.random.random((5,3))
'''
Another way:
random_2d_float_arr = np.random.uniform(5,10, size=(5,3))
'''
print(random_2d_float_arr)

[[8.74644132 5.05533209 6.30029112]
 [7.82719638 5.83656737 8.62494695]
 [7.91309762 8.69221266 6.30082794]
 [6.05515282 8.80131216 6.55562104]
 [7.77815242 8.52784336 6.59865329]]


In [3]:
#21 Print or show only 3 decimal places of the numpy array rand_arr
rand_arr = np.random.uniform()
np.set_printoptions(precision=3)
print(rand_arr)

0.8971484186768155


In [5]:
#22 Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)
print(rand_arr)

[[0.001 0.    0.   ]
 [0.001 0.    0.   ]
 [0.001 0.001 0.   ]]


In [6]:
#23 Limit the number of items printed in python numpy array a to a maximum of 6 elements.
arr=np.arange(15)
np.set_printoptions(threshold=6)
print(arr)

[ 0  1  2 ... 12 13 14]


In [8]:
#24 Print the full numpy array a without truncating.
import sys
np.set_printoptions(threshold=sys.maxsize)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
#25 Import the iris dataset keeping the text intact.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

url_local = 'C:/Users/Admin/Desktop/Learning/Data Science/DataSets'
# iris_local = np.fromfile(url_local,sep=',')

names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:4])
# print(iris_local[:4])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']]


In [6]:
#26 Extract the text column species from the 1D iris imported in previous question.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species = [i[4] for i in iris]
print(species[:5])

[b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa']


In [21]:
#27 Convert the 1D iris to 2D array iris_2d by omitting the species text field.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None,encoding=None)
print(iris_1d[4])
iris_2d = [list(i)[:4] for i in iris_1d]
'''
Alternative way:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
'''
print(iris_2d[:4])

## Need to check this. 

(5., 3.6, 1.4, 0.2, 'Iris-setosa')
[[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2]]


In [11]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype=None,encoding=None,usecols=[0])

In [25]:
#28  Find the mean, median, standard deviation of iris's sepallength (1st column)

mean=np.mean(sepallength)
median=np.median(sepallength)
standard_deviation=np.std(sepallength)

print(mean)
print(median)
print(standard_deviation)

5.843333333333334
5.8
0.8253012917851409


In [26]:
#29 Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

sl_min,sl_max = sepallength.min(),sepallength.max() # diff=sepallength.ptp() #peak to peak
normalized_sepallength = (sepallength-sl_min)/(sl_max-sl_min)
#Find is there any other way
print(normalized_sepallength)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [23]:
#30 Compute the softmax score of sepallength.*
'''
Need to understand.
https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python
'''

'\nNeed to understand.\n'

In [27]:
#31 Find the 5th and 95th percentile of iris's sepallength

percentiles = np.percentile(sepallength,[5,95])
print(percentiles)

[4.6   7.255]


In [10]:
#32 Insert np.nan values at 20 random positions in iris_2d dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
i,j=np.where(iris_2d)
iris_2d[np.random.choice((i),20),np.random.choice((j),20)]=np.nan
'''
Alternative method:
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
'''
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' nan]
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [54]:
#33 Find the number and position of missing values in iris_2d's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

missing_positions = np.where(np.isnan(iris_2d[:,0]))
print(len(missing_positions[0]))
print(missing_positions)

4
(array([14, 34, 79, 87], dtype=int32),)


In [55]:
#34 Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])

filtered_iris = iris_2d[np.where((iris_2d[:,2]>1.5)&(iris_2d[:,0]<5.0))]
print(filtered_iris)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [61]:
#35 Select the rows of iris_2d that does not have any nan value.
perfect_iris_2d_bools =iris_2d[list(set(np.where(~np.isnan(iris_2d[:,:]))[0]))]
'''
Another way
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
print(iris_2d[any_nan_in_row][:5])

'''
print(perfect_iris_2d_bools[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [67]:
#36 Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])
correlation = np.corrcoef(iris_2d[:,0],iris_2d[:,2])[0,1]
print(correlation)

0.871754157304871


In [68]:
#37 Find out if iris_2d has any missing values
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])
any_missing_values = np.isnan(iris_2d).any()
print(any_missing_values)

False


In [70]:
#38 Replace all ccurrences of nan with 0 in numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.random.seed(200)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)]=0
print(iris_2d[:10,:])

[[5.1 3.5 1.4 0.2]
 [0.  3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  0.  1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [79]:
#39  Find the unique values and the count of unique values in iris's species
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
species = iris[:,4]
unique_species = np.unique(species,return_counts=True)
print(unique_species)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([50, 50, 50]))


In [5]:
#40 Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large'
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
petal_length = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[2])
petal_length_bin = np.digitize(petal_length,[0,3,5,10])
label_map = {1:'small',2:'medium',3:'large',4:np.nan}
petal_length_categorized = [label_map[x] for x in petal_length_bin]
print(petal_length_categorized[:10])

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small']


In [7]:
#41 Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3
out = np.hstack([iris_2d, volume[:,np.newaxis]])
print(out[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 38.13265162927291]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 35.200498485922445]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 30.0723720777127]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 33.238050274980004]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 36.65191429188092]
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa' 51.911677007917746]
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa' 31.022180256648003]
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa' 39.269908169872416]
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa' 28.38324242763259]
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa' 37.714819806345474]]


In [9]:
#42 Randomly sample iris's species such that setose is twice the number of versicolor and virginica
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species = iris[:, 4]

np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
print(species_out)
print(np.unique(species_out, return_counts=True))


''' Need to look
Another way:
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))
#Approach 2 is preferred because it creates an index variable that can be used to sample 2d tabular data.
'''

['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor

In [19]:
#43 What is the value of second longest petallength of species setosa
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
petallength_groupby_setosa = iris[np.where(iris[:,4]==b'Iris-setosa')][:,2].astype('float')
petallength_groupby_setosa_2max = np.unique(np.sort(petallength_groupby_setosa))[-2]
print(petallength_groupby_setosa_2max)

1.7


In [22]:
#44 Sort the iris dataset based on sepallength column.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sorted_iris_by_sepallength = iris[iris[:,0].argsort()]
print(sorted_iris_by_sepallength[:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [26]:
#45 Find the most frequent value of petal length (3rd column) in iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
vals, counts = np.unique(iris[:, 2], return_counts=True)
most_freq_petallength = vals[np.argmax(counts)]
print(most_freq_petallength)

b'1.5'


In [29]:
#46 Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
value = np.argwhere(iris[:,3].astype('float')>1.0)[0]
print(value)

[50]


In [30]:
#47  From the array a, replace all values greater than 30 to 30 and less than 10 to 10
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
#clip function *
a=np.clip(a, a_min=10, a_max=30)
'''By using where also we can do it'''
print(a)

[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [37]:
#48 Get the positions of top 5(n) maximum values in a given array a
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
positions = a.argsort()[:-6:-1]
print(positions)

[15 10  3  7 18]


In [49]:
#49 Compute the counts of unique values row-wise.
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
out=[]
for res in [np.unique(a,return_counts=True) for a in arr]:
    val,count=res
    d={val[i]:count[i] for i in range(len(val))}
    out.append([d[x] if x in d else 0 for x in range(1,11)])
print(out)

[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0], [2, 1, 3, 0, 1, 0, 1, 0, 1, 1], [0, 3, 0, 2, 3, 1, 0, 1, 0, 0], [1, 0, 2, 1, 0, 1, 0, 2, 1, 2], [2, 2, 2, 0, 0, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]


In [5]:
#50 Convert array_of_arrays into a flat linear 1d array.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

# arr=np.arange(10).reshape(5,2)
# print(arr.ravel())
# https://stackoverflow.com/questions/28930465/what-is-the-difference-between-flatten-and-ravel-functions-in-numpy
array_of_arrays = np.array([arr1, arr2, arr3])
arr = np.concatenate(array_of_arrays)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
#51 Compute the one-hot encodings (dummy binary variables for each unique value in the array)
np.random.seed(101) 
arr = np.random.randint(1,10, size=6)
print(arr)
print(arr[:, None])
print((arr[:, None] == np.unique(arr)).view(np.int8))


#Important.....*

[2 7 8 9 5 9]
[[2]
 [7]
 [8]
 [9]
 [5]
 [9]]
[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 0 1]]


In [27]:
#52  Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

#Try another way

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


In [44]:
#53 Create group ids based on a given categorical variable. Use the following sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
array=[np.where(i)[0][0] for i in (species_small[:,None] == np.unique(species_small))]
print(array)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


In [46]:
#54  Create the ranks for the given numeric array a.
Need to understand what is ranks.

SyntaxError: invalid syntax (<ipython-input-46-19a092360c0b>, line 2)

In [47]:
#55 Create a rank array of the same shape as a given numeric array a.
Need to understand what is ranks.

SyntaxError: invalid syntax (<ipython-input-47-481690461177>, line 2)

In [52]:
#56  Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
#method 1
max_row = [i.max() for i in a]
print(max_row)

#method2
max_row = np.amax(a,axis=1)
print(max_row)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9, 8, 6, 3, 9]
[9 8 6 3 9]


In [58]:
#57 Compute the min-by-max for each row for given 2d numpy array
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
res = np.apply_along_axis(lambda x : np.min(x)/np.max(x),axis=1,arr=a)
print(res)

[0.44444444 0.125      0.5        1.         0.11111111]


In [59]:
#58 Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.
